shared:
  KT_THEME: 'metronic'

  # Theme layout templates directory

  KT_THEME_LAYOUT_DIR: 'layout'


  # Theme Mode
  # Value: light | dark | system

  KT_THEME_MODE_DEFAULT: 'light'
  KT_THEME_MODE_SWITCH_ENABLED: true


  # Theme Direction
  # Value: ltr | rtl

  KT_THEME_DIRECTION: 'ltr'


  # Theme Assets

  KT_THEME_ASSETS:
    "favicon": "logos/favicon.ico"
    "fonts": [
      'https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700',
    ]
    "css": [
      "global/plugins.bundle.css",
      "style.bundle.css"
    ]
    "js": [
      "global/plugins.bundle.js",
      "scripts.bundle.js",
    ]


  # Theme Vendors

  KT_THEME_VENDORS:
    "datatables": {
      "css": [
        "custom/datatables/datatables.bundle.css"
      ],
      "js": [
        "custom/datatables/datatables.bundle.js"
      ]
    }
    "formrepeater": {
      "js": [
        "custom/formrepeater/formrepeater.bundle.js"
      ]
    }
    "fullcalendar": {
      "css": [
        "custom/fullcalendar/fullcalendar.bundle.css"
      ],
      "js": [
        "custom/fullcalendar/fullcalendar.bundle.js"
      ]
    }
    "flotcharts": {
      "js": [
        "custom/flotcharts/flotcharts.bundle.js"
      ]
    }
    "google-jsapi": {
      "js": [
        "//www.google.com/jsapi"
      ]
    }
    "tinymce": {
      "js": [
        "custom/tinymce/tinymce.bundle.js"
      ]
    }
    "ckeditor-classic": {
      "js": [
        "custom/ckeditor/ckeditor-classic.bundle.js"
      ]
    }
    "ckeditor-inline": {
      "js": [
        "custom/ckeditor/ckeditor-inline.bundle.js"
      ]
    }
    "ckeditor-balloon": {
      "js": [
        "custom/ckeditor/ckeditor-balloon.bundle.js"
      ]
    }
    "ckeditor-balloon-block": {
      "js": [
        "custom/ckeditor/ckeditor-balloon-block.bundle.js"
      ]
    }
    "ckeditor-document": {
      "js": [
        "custom/ckeditor/ckeditor-document.bundle.js"
      ]
    }
    "draggable": {
      "js": [
        "custom/draggable/draggable.bundle.js"
      ]
    }
    "fslightbox": {
      "js": [
        "custom/fslightbox/fslightbox.bundle.js"
      ]
    }
    "jkanban": {
      "css": [
        "custom/jkanban/jkanban.bundle.css"
      ],
      "js": [
        "custom/jkanban/jkanban.bundle.js"
      ]
    }
    "typedjs": {
      "js": [
        "custom/typedjs/typedjs.bundle.js"
      ]
    }
    "cookiealert": {
      "css": [
        "custom/cookiealert/cookiealert.bundle.css"
      ],
      "js": [
        "custom/cookiealert/cookiealert.bundle.js"
      ]
    }
    "cropper": {
      "css": [
        "custom/cropper/cropper.bundle.css"
      ],
      "js": [
        "custom/cropper/cropper.bundle.js"
      ]
    }
    "vis-timeline": {
      "css": [
        "custom/vis-timeline/vis-timeline.bundle.css"
      ],
      "js": [
        "custom/vis-timeline/vis-timeline.bundle.js"
      ]
    }
    "jstree": {
      "css": [
        "custom/jstree/jstree.bundle.css"
      ],
      "js": [
        "custom/jstree/jstree.bundle.js"
      ]
    }
    "prismjs": {
      "css": [
        "custom/prismjs/prismjs.bundle.css"
      ],
      "js": [
        "custom/prismjs/prismjs.bundle.js"
      ]
    }
    "leaflet": {
      "css": [
        "custom/leaflet/leaflet.bundle.css"
      ],
      "js": [
        "custom/leaflet/leaflet.bundle.js"
      ]
    }
    "amcharts": {
      "js": [
        "https://cdn.amcharts.com/lib/5/index.js",
        "https://cdn.amcharts.com/lib/5/xy.js",
        "https://cdn.amcharts.com/lib/5/percent.js",
        "https://cdn.amcharts.com/lib/5/radar.js",
        "https://cdn.amcharts.com/lib/5/themes/Animated.js"
      ]
    }
    "amcharts-maps": {
      "js": [
        "https://cdn.amcharts.com/lib/5/index.js",
        "https://cdn.amcharts.com/lib/5/map.js",
        "https://cdn.amcharts.com/lib/5/geodata/worldLow.js",
        "https://cdn.amcharts.com/lib/5/geodata/continentsLow.js",
        "https://cdn.amcharts.com/lib/5/geodata/usaLow.js",
        "https://cdn.amcharts.com/lib/5/geodata/worldTimeZonesLow.js",
        "https://cdn.amcharts.com/lib/5/geodata/worldTimeZoneAreasLow.js",
        "https://cdn.amcharts.com/lib/5/themes/Animated.js"
      ]
    }
    "amcharts-stock": {
      "js": [
        "https://cdn.amcharts.com/lib/5/index.js",
        "https://cdn.amcharts.com/lib/5/xy.js",
        "https://cdn.amcharts.com/lib/5/themes/Animated.js"
      ]
    }
    "bootstrap-select": {
      "css": [
        "custom/bootstrap-select/bootstrap-select.bundle.css"
      ],
      "js": [
        "custom/bootstrap-select/bootstrap-select.bundle.js"
      ]
    }


production:

development:
